tenjin:
  persistence:
    size: "6Gi" # Size of the storage
    storageClassName: "standard" # Name of the storage class (adjust based on your cluster)
  service:
    type: NodePort
    port: 8080
elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteOnce
    storageClassName: standard
    size: 5Gi
postgres:
  image: ""
  persistence:
    size: 10Gi # Storage size
    accessModes: ReadWriteOnce # Access mode
    storageClassName: standard # StorageClass for dynamic provisioning
environment:
  POSTGRES_DB: tenjin
  POSTGRES_USER: yethi
  POSTGRES_PASSWORD: Yethi123
  ORACLE_USER: tenjin
  ORACLE_PASSWORD: tenjin

tenjinkairo:
  image: "registry.gitlab.com/yethi/rnd/gen-ai/copilot-service/tenjin-copilot-service:4.17.2"
  VECTOR_STORE_ID: ""
  TEST_GEN_INSTANCE: ""
  TEST_GEN_OPENAI_API_KEY: ""
  OPENAI_API_KEY: ""
  LANGSMITH_API_KEY: ""

tenjincore:
  image: "registry.gitlab.com/yethi/tenjin-enterprise/devops/docker_image_builder/tenjin-enterprise:4.17.2"
  TENJIN_DEFAULT_USER_PASSWORD: ""
  TENJIN_BASE_URL: ""
  TENJIN_ALLOWED_URL: ""
  TENJIN_AI_HOST: ""
  OPENAI_API_KEY: ""
  TENJIN_SCHEDULER_RETENTION_DAYS: ""
  TENJIN_SCHEDULER_CRON: ""
  MAIL_PWD: ""
  COOKIE_SECURE: ""
  SSL_ENABLED: ""

pgadmin:
  image: dpage/pgadmin4:8.5
  email: admin@yethi.in
  password: admin123

  persistence:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClassName: standard

addCopilotDeployment: false
addCopilotConfig: false
addCopilotService: false