database:
  type: postgres # postgres | oracle

tenjin:
  persistence:
    accessModes:
      - ReadWriteMany # ReadWriteOnce 
    size: "6Gi"
    storageClassName: <nfs-storageclassname>
  service:
    type: NodePort
    port: 8080

elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteMany
    storageClassName: <nfs-storageclassname>
    size: 5Gi

postgres:
  enabled: true
  image: "pgvector/pgvector:pg17-trixie"
  persistence:
    size: 10Gi
    accessModes: ReadWriteMany
    storageClassName: <nfs-storageclassname>

environment:
  # PostgreSQL
  POSTGRES_DB: tenjin
  POSTGRES_USER: yethi
  POSTGRES_PASSWORD: Yethi123

  # Oracle
  ORACLE_HOST: ""
  ORACLE_PORT: "1521"
  ORACLE_SERVICE: ""
  ORACLE_USER: ""
  ORACLE_PASSWORD: ""

  # Elasticsearch
  ELASTIC_PORT: "9200"
  ELASTIC_USERNAME: "elastic"
  ELASTIC_SECURETYPE: "http"

tenjinkairo:
  image: "registry.yethi.in/products/tenjin-workbench/copilot-service:epic-te-8091"
  VECTOR_STORE_ID: ""
  TEST_GEN_INSTANCE: ""
  TEST_GEN_OPENAI_API_KEY: ""
  OPENAI_API_KEY: ""
  LANGSMITH_API_KEY: ""
  storage:
    size: 10Gi
    accessMode: ReadWriteMany
    storageClassName: <nfs-storageclassname>

tenjincore:
  image: "registry.yethi.in/products/tenjin-workbench/tenjin-workbench:dev-te-8091--latest"
  TENJIN_DEFAULT_USER_PASSWORD: ""
  TENJIN_BASE_URL: ""
  TENJIN_ALLOWED_URL: ""
  TENJIN_AI_HOST: ""
  OPENAI_API_KEY: ""
  TENJIN_SCHEDULER_RETENTION_DAYS: ""
  TENJIN_SCHEDULER_CRON: ""
  MAIL_PWD: ""
  COOKIE_SECURE: "false"
  SSL_ENABLED: "false"

pgadmin:
  image: "dpage/pgadmin4:8.5"
  email: admin@yethi.in
  password: admin123
  persistence:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClassName: standard