apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenjin-workbench-index-testing
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://yethi-tech.github.io/tenjin-workbench-on-premises
      chart: tenjin-workbench
      targetRevision: "4.17.3"

      helm:
        releaseName: tenjin-workbench-index-testing
        valueFiles:
          - $values/argocd/values/postgres-support-values.yaml

    - repoURL: https://github.com/yethi-tech/tenjin-workbench-on-premises.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: tenjin-workbench-index-testing

  syncPolicy:
    syncOptions:
      - CreateNamespace=true