tenjin:
  persistence:
    size: "6Gi" # Size of the storage
    storageClassName: "standard" # Name of the storage class (adjust based on your cluster)
  service:
    type: NodePort
    port: 8080
elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteOnce
    storageClassName: standard
    size: 5Gi
postgres:
  image: "postgres:13"
  persistence:
    size: 10Gi # Storage size
    accessModes: ReadWriteOnce # Access mode
    storageClassName: standard # StorageClass for dynamic provisioning
environment:
  POSTGRES_DB: tenjin
  POSTGRES_USER: yethi
  POSTGRES_PASSWORD: Yethi123
  ORACLE_USER: tenjin
  ORACLE_PASSWORD: tenjin

tenjinkairo:
  image: "yethitech/tenjin-kairo:4.17.2"
  VECTOR_STORE_ID: "vs_6a1ebb74d1008191a069d61abfdf4e14"
  TEST_GEN_INSTANCE: "enterprise"
  TEST_GEN_OPENAI_API_KEY: ""
  OPENAI_API_KEY: ""
  LANGSMITH_API_KEY: ""

tenjincore:
  image: "registry.gitlab.com/yethi/tenjin-enterprise/devops/docker_image_builder/tenjin-enterprise:4.17.3"
  TENJIN_DEFAULT_USER_PASSWORD: "Welcome@2026"
  TENJIN_BASE_URL: ""
  TENJIN_ALLOWED_URL: ""
  OPENAI_API_KEY: ""
  TENJIN_SCHEDULER_RETENTION_DAYS: "30"
  TENJIN_SCHEDULER_CRON: "0 0 * * * ?"
  MAIL_PWD: ""
  COOKIE_SECURE: "false"
  SSL_ENABLED: "false"

pgadmin:
  image: dpage/pgadmin4:8.5
  email: admin@yethi.in
  password: admin123

  persistence:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClassName: standard
