apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-copilot
  labels:
    app: copilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copilot
  template:
    metadata:
      labels:
        app: copilot
    spec:
      containers:
        - name: copilot
          image: {{ .Values.tenjinkairo.image | default "registry.gitlab.com/yethi/rnd/gen-ai/copilot-service/tenjin-copilot-service:4.17.2" }}
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 4Gi

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-copilot-config
