apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-init-job
spec:
  schedule: "0 0 1 1 *"  # Run at 00:00 on Jan 1st every year
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: db-updater
              image: bitnami/postgresql:13
              command:
                - /bin/sh
                - -c
                - |-
                  echo "Waiting for PostgreSQL to be ready...";
                  until pg_isready -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin"; do
                    sleep 5;
                  done;

                  echo "Sleeping extra 20s for services to settle...";
                  sleep 20;

                  echo "Running query 1...";
                  PGPASSWORD="Yethi123" psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "INSERT INTO sys_users_password_history (user_id, password_history, updated_at) SELECT id, password, NOW() FROM sys_users WHERE password IS NOT NULL;"
                  sleep 20;

                  echo "Running query 2...";
                  PGPASSWORD="Yethi123" psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "UPDATE prj_users SET prj_role_mapped = 101 WHERE prj_role_mapped != 100;"
                  sleep 20;

                  echo "Running query 3...";
                  PGPASSWORD="Yethi123" psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "DELETE FROM common_project_role_permissions;"
                  sleep 20;

                  echo "Running query 4...";
                  PGPASSWORD="Yethi123" psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "DELETE FROM project_roles_permissions;"
                  sleep 20;

                  echo "Running query 5...";
                  PGPASSWORD="Yethi123" psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "DELETE FROM prj_roles WHERE id NOT IN (100, 101);"
                  sleep 20;

                  echo "All queries executed successfully."
