---
apiVersion: batch/v1
kind: Job
metadata:
  name: tenjin-db-update
  annotations:
    helm.sh/hook: post-upgrade
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-updater
          image: postgres:13
          command:
            - sh
            - -c
            - >
              echo "Waiting for PostgreSQL to be ready..." ;

              until pg_isready -h "{{ .Release.Name }}-postgres" -U "yethi" -d "tenjin"; do
                sleep 5;
              done;

              echo "PostgreSQL is ready. Running database update..." ;

              PGPASSWORD="Yethi123" psql -h "{{ .Release.Name }}-postgres" -U "yethi" -d "tenjin" -c "{{ .Values.dbUpdateQuery | squote }}"
