apiVersion: batch/v1
kind: Job
metadata:
  name: tenjin-db-update
  annotations:
    "helm.sh/hook": post-upgrade  # Runs after each `helm upgrade`
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-updater
          image: postgres:13
          command:
            - "sh"
            - "-c"
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until pg_isready -h tenjin-postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
                sleep 5;
              done;
              echo "PostgreSQL is ready. Running database update...";
              PGPASSWORD="$POSTGRES_PASSWORD" psql -h tenjin-postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "{{ .Values.dbUpdateQuery }}"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.environment.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.environment.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.environment.POSTGRES_PASSWORD }}"
