apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-filebeat-config
  namespace: tenjin-workbench-vulnerability
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              default_indexers.enabled: true
              default_matchers.enabled: false
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts:
        - "http://{{ .Release.Name }}-elasticsearch.tenjin-workbench-vulnerability.svc.cluster.local:9200"
      username: "elastic"
      index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

    setup.template:
      enabled: false
      name: "filebeat"
      pattern: "filebeat-*"
      overwrite: true

    setup.ilm:
      enabled: true
      policy_name: "filebeat"
      rollover_alias: "filebeat"
