apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-filebeat-sa
  namespace: tenjin-workbench-vulnerability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-filebeat-sa
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-filebeat-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-filebeat-sa
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-filebeat-sa
    namespace: tenjin-workbench-vulnerability