apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
  labels:
    app: {{ .Release.Name }}-pgadmin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081          # Service port (used to access pgAdmin)
      targetPort: 8081    # Container port inside pgAdmin pod
  selector:
    app: {{ .Release.Name }}-pgadmin
