apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tenjin-ai
  labels:
    name: {{ .Release.Name }}-tenjin-ai
data:
  HOST: "http://192.168.16.88"
  PORT: "30557"
  OPENAI_API_KEY: "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"
  db_user: "yethi"
  db_password: "Yethi123"
  db_host: "{{ .Release.Name }}-postgres"
  db_port: "5432"
  db_name: "tenjin"
  db_type: "postgres"
  db_schema: "public"
