apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tenjin-ai
  labels:
    name: {{ .Release.Name }}-tenjin-ai
spec:
  replicas: 1
  selector:
    matchLabels:
       app: tenjin-ai
  template:
    metadata:
      labels:
        app: tenjin-ai
    spec:
      containers:
        - name: tenjin-ai
          image: registry.gitlab.com/yethi/tenjin-ai/prototypes/test-process-automation/design/test-case-generation-int:orcale_test
          imagePullPolicy: Always
          resources:
            limits:
              memory: "4Gi"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-tenjin-ai
          ports:
            - containerPort: 8022
      imagePullSecrets:
        - name: gitlab-auth