apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tenjin-ai
  labels:
    name: {{ .Release.Name }}-tenjin-ai
data:
  HOST: "http://192.168.16.88"
  PORT: "30557"
  OPENAI_API_KEY: "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"
  db_user: "{{ .Values.environment.POSTGRES_USER }}"
  db_password: "{{ .Values.environment.POSTGRES_PASSWORD }}"
  db_host: "{{ .Release.Name }}-postgres"
  db_port: "5432"
  db_name: "{{ .Values.environment.POSTGRES_DB }}"
  db_type: "postgres"
  db_schema: "tenjin"
  instance: "enterprise"
  llm_provider: "openai"
  openai_model: "gpt-4.1"
