apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tenjin-ai
  labels:
    name: {{ .Release.Name }}-tenjin-ai
data:
  HOST: "http://192.168.16.88"
  PORT: "30557"
  OPENAI_API_KEY: ""
  db_user: "yethi"
  db_password: "Yethi123"
  db_host: "{{ .Release.Name }}-postgres"
  db_port: "5432"
  db_name: "tenjin"
  db_type: "postgres"
  db_schema: "public"