apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tenjin-core
  labels:
    name: {{ .Release.Name }}-tenjin-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenjin
  template:
    metadata:
      labels:
        app: tenjin
    spec:
      containers:
        - name: tenjin-core
          image: yethitech/tenjin-enterprise:4.10.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmaptenjin
          volumeMounts:
            - name: tenjin-data-volume
              mountPath: /root
      volumes:
        - name: tenjin-data-volume
          persistentVolumeClaim:
            claimName: tenjin-data-volume
      imagePullSecrets:
        - name: gitlab-auth
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - >
              until nc -zv {{ .Release.Name }}-elasticsearch 9200 && nc -zv 192.168.3.136 1521; do
                echo "Waiting for Elasticsearch and Oracle DB to be available..."
                sleep 5
              done

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenjin-data-volume
  labels:
    app: tenjin
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tenjin.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.tenjin.persistence.storageClassName | default "standard" }}
