apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmaptenjin

data:

{{ if eq .Values.database.type "postgres" }}
  # PostgreSQL
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.environment.POSTGRES_DB }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.environment.POSTGRES_USER }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.environment.POSTGRES_PASSWORD }}"
{{ else if eq .Values.database.type "oracle" }}
  # Oracle
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "oracle.jdbc.OracleDriver"
  SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@//{{ .Values.environment.ORACLE_HOST }}:{{ .Values.environment.ORACLE_PORT }}/{{ .Values.environment.ORACLE_SERVICE }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.environment.ORACLE_USER }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.environment.ORACLE_PASSWORD }}"
{{ end }}

  # Elasticsearch
  TENJIN_ELASTIC_HOST: "{{ .Release.Name }}-elasticsearch"
  TENJIN_ELASTIC_PORT: "{{ .Values.environment.ELASTIC_PORT | default "9200" }}"
  TENJIN_ELASTIC_USERNAME: "{{ .Values.environment.ELASTIC_USERNAME | default "elastic" }}"
  TENJIN_ELASTIC_SECURETYPE: "{{ .Values.environment.ELASTIC_SECURETYPE | default "http" }}"

  # Tenjin Core
  TENJIN_DEFAULT_USER_PASSWORD: "{{ .Values.tenjincore.TENJIN_DEFAULT_USER_PASSWORD | default "Welcome@2025" }}"
  TENJIN_BASE_URL: "{{ .Values.tenjincore.TENJIN_BASE_URL | default "http://localhost" }}"
  TENJIN_ALLOWED_URL: "{{ .Values.tenjincore.TENJIN_ALLOWED_URL | default "http://localhost" }}"

  TENJIN.AI-HOST: "http://{{ .Release.Name }}-copilot:8000"
  tenjin.copilot.service.url: "http://{{ .Release.Name }}-copilot:8000"

  OPENAI_API_KEY: "{{ .Values.tenjincore.OPENAI_API_KEY | default "[ENCRYPTION_KEY]" }}"
  OPENAI_MODEL: "gpt-5.2"

  TENJIN_SCHEDULER_ENABLED: "Y"
  TENJIN_LONGPOLLING_SCHEDULER_ENABLED: "Y"
  TENJIN_SCHEDULER_RETENTION_DAYS: "{{ .Values.tenjincore.TENJIN_SCHEDULER_RETENTION_DAYS | default "" }}"
  TENJIN_SCHEDULER_CRON: "{{ .Values.tenjincore.TENJIN_SCHEDULER_CRON | default "0 0 * * * ?" }}"

  TENJIN_ELASTIC_IMPORT_SIZE: "300"
  TENJIN_INDEX_THREADS: "10"
  TENJIN_INDEX_CORE_THREADS: "25"
  TENJIN_INDEX_MAX_THREADS: "50"
  TENJIN_INDEX_QUEUE_CAPACITY: "200"
  TENJIN_INDEX_RETRY_DELAY: "1000"

  TENJIN_JACKSON_MAX_STRING_LENGTH: "20000"

  MAIL_PWD: "{{ .Values.tenjincore.MAIL_PWD | default "" }}"

  TENJIN_SCHEDULER_AWAIT_TERMINATION_ENABLED: "true"
  TENJIN_SCHEDULER_AWAIT_TERMINATION_PERIOD: "180"

  COOKIE_SECURE: "{{ .Values.tenjincore.COOKIE_SECURE | default "false" }}"
  SSL_ENABLED: "{{ .Values.tenjincore.SSL_ENABLED | default "false" }}"